application: plurkii
version: v2
runtime: python
api_version: 1

handlers:
## Favion url.
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon

## Images files.
- url: /images
  static_dir: static/images
- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)

## CSS
- url: /css
  static_dir: static/css
- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

## Main WSGI
- url: .*
  script: main_v2.py
  #secure: always
  login: admin
