application: plurkii
version: v2
runtime: python
api_version: 1

default_expiration: "1d"

handlers:
## Favion url.
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  mime_type: image/x-icon
  upload: static/images/favicon.ico

## Images files.
- url: /images
  static_dir: static/images
- url: /images/(.*)
  static_files: static/images/\1
  upload: static/images/(.*)

## CSS
- url: /css
  static_dir: static/css
- url: /css/(.*)
  static_files: static/css/\1
  mime_type: text/css
  upload: static/css/(.*)

## Firefox add-ons extension.
- url: /plurkiisearch\.xml
  static_files: static/plurkiisearch.xml
  upload: static/plurkiisearch.xml

## Main WSGI
- url: .*
  script: main_v2.py
  #secure: always
  #login: admin

inbound_services:
- warmup
